# Generated by Django 3.2.9 on 2021-12-02 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_alter_aluno_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='comentario',
            field=models.TextField(blank=True),
        ),
    ]
